apiVersion: apps/v1
kind: Deployment
metadata:
  name: stackdriver-example-backend
  labels:
    app: stackdriver-example
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stackdriver-example
      tier: backend
  template:
    metadata:
      labels:
        app: stackdriver-example
        tier: backend
    spec:
     initContainers:
      - name: init-db-ready
        image: mongo:4
        command: ['/bin/sh', '-c']
        args:
          - echo "Waiting for mongodb to start...";until (mongo --host stackdriver-example-mongodb:27017 >/dev/null 2>&1) do echo "Waiting for connection for 2 sec."; sleep 2; done
     containers:
      - name: backend
        image: stackdriver-example-backend
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: GUESTBOOK_DB_ADDR
          value: "stackdriver-example-mongodb:27017"
